### ISSUE TITLE
Cache Smart Textures

### ISSUE THREAD

**Issue by goldfire** [Irrelon/ige#430]
We've been struggling with this one for some time and were curious if anyone else had found a solution. Here's a very basic example to illustrate the problem:

```javascript
var tex = new IgeTexture({
  render: function(ctx) {
    ctx.fillStyle = 'green';
    ctx.fill();
  }
});

var bg = new IgeScene2d()
  .texture(tex)
  .width(100)
  .height(100)
  .mount(mount);
```

This works fine and displays the green box as expected. However, if we set `cache` to `true` on `bg`, it goes blank. After debugging more, the cache canvas is actually completely blank, even though the `ctx` being passed into the `render` method is correct from the cache canvas. Any ideas?

**Comment by raldred** [comment]
Hello, Not 100% sure what's going on in the example you've provided as I too couldn't get it to work.
I suspect something interenal to the canvas API because there's no shape being drawn.

Replacing the Texture with the following and it works fine:

    var tex = new IgeTexture({
        render: function(ctx) {
            ctx.fillStyle = 'green';
            ctx.fillRect(20,20,150,100);
            // ctx.fill();
        }
    });

**Comment by goldfire** [comment]
Good call, not sure why I didn't think to try that! Looking back it now makes total sense why that is the case. Thanks!

**Comment by Irrelon** [comment]
LOL I also looked at that and didn't spot it! Good call @raldred :)
