### ISSUE TITLE
'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead. game.js:10 

### ISSUE THREAD

**Issue by darianhickman** [Irrelon/ige#443]
I get this error message and developer console in Chrome.  
'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead. game.js:10

**Comment by Sandstedt** [comment]
Same here. The error is in `IgeTexture.js` on multiple places. Will make a pull request..

**Comment by Irrelon** [comment]
Pull request merged. Thanks!
