### ISSUE TITLE
Changes to Canvas Rendering

### ISSUE THREAD

**Issue by ButsAndCats** [Irrelon/ige#445]
Chrome console log gives me this message. Not sure if this is applicable to other browsers I haven't tested.
`CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated and will be removed in M55, around November 2016. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead. See https://www.chromestatus.com/features/5639849247768576 for more details.`

The related file is **IgeTextureMap.js** _line 500_

**Comment by raldred** [comment]
Hi George thanks for the report. I'll patch this later. We will still need
to support older versions that still use the prefixed version.

**Comment by Sandstedt** [comment]
The webkit prefixes is now removed everywhere. See pull request here: #454

**Comment by raldred** [comment]
Hi Jonas, agreed I just needed to be sure. I merged #454 earlier in the
week.

**Comment by Sandstedt** [comment]
@raldred I know, just wanted to close this issue :) But great that you did some more research.
