### ISSUE TITLE
Show Stats depreciation

### ISSUE THREAD

**Issue by ButsAndCats** [Irrelon/ige#446]
I understand that show stats has been replaced by `ige.addComponent(IgeEditorComponent);`.

Many of the examples are still using show stats, would it be beneficial if I created a PR replacing them or is there a reason for them not being changed?

**Comment by Irrelon** [comment]
Hey ya!

Does showStats still work or is it now completely removed from the engine? If it is completely removed then I think it would be beneficial.

If showStats still works and displays the engine stats at runtime then I think it is ok to leave them. Ultimately the editor component is a different function that happens to include a stats display. It might not be useful to everyone though.

**Comment by ButsAndCats** [comment]
All it does is this:
```
	showStats: function () {
		this.log('showStats has been removed from the ige in favour of the new editor component, please remove this call from your code.');
	},
```
Sooooo, I'm gonna go ahead and make that pull request.

**Comment by Irrelon** [comment]
Wonderful thanks 👍
