### ISSUE TITLE
Mongo Connection variables

### ISSUE THREAD

**Issue by ButsAndCats** [Irrelon/ige#448]
In `examples/19.2-database-mongodb` the database connection variables are set in `ServerConfig.js`

```
var config = {
	include: [
		//{name: 'ServerNetworkEvents', path: './gameClasses/ServerNetworkEvents'}
	],
	db: {
		type: 'mongo',
		host: 'localhost',
		user: '',
		pass: '',
		dbName: 'test'
	}
};
```
However despite me setting custom variables it seems as though they aren't being passed to the server and the default values set in `/server/node_modules/mongodb/lib/mongodb` are being used instead. What is the correct way of defining the variables? Can someone else test this as I may be missing something.

**Comment by ButsAndCats** [comment]
Also noticed that the example uses the API Class IgeMongoDbComponent but there is no documentation for this on the website or the inside the repository.

**Comment by Irrelon** [comment]
Hi George, I suspect that the mongodb stuff is massively out of date and probably much easier to add and manage a mongo connection with your own code.

**Comment by ButsAndCats** [comment]
Okay, thanks for the reply. If I find time I will try and put together a tutorial.
