### ISSUE TITLE
IgeUiTextBox DOM equivalent not being properly disposed

### ISSUE THREAD

**Issue by JacobPersi** [Irrelon/ige#449]
If a IgeUiTextBox is focused while the object is removed (via the destroy function) the '_domElement' will remain, resulting in any subsequent IgeUiTextBoxes to behave incorrectly. 

For example:
```
var textbox = new IgeUiTextBox()
	.id("textBox")
	.mount(ige.$("uiScene"));

textbox.focus();
textbox.destroy();
```

**Comment by JacobPersi** [comment]
Fix is simple, utilize the preexisting 'blur' function to remove the DOM input element.

```
destroy: function () {
	this.blur();
	IgeUiElement.prototype.destroy.call(this);
}
```

**Comment by Irrelon** [comment]
Ahh awesome. Is there any chance you can create a pull request for this?
