### ISSUE TITLE
Active development

### ISSUE THREAD

**Issue by gremz** [Irrelon/ige#473]
I'm looking to use this engine for a project and wanted to see if this project is expected to receive regular updates/fixes.

**Comment by Irrelon** [comment]
Hi ya, IGE occasionally gets pull requests from the community. There are a few companies using it actively so we see updates from them as well. My time working on the engine is limited to about 1 hour every month so very little updates come from me the creator of the engine.

**Comment by gremz** [comment]
Good to know. Thanks for the status!
