### ISSUE TITLE
IGE-ES6 - Composite caching no longer works

### ISSUE THREAD

**Issue by beyond-code-github** [Irrelon/ige#477]
It seems that composite caching is broken in the new engine. I have checked against the HEAD of the current es6 branch as well to ensure that it wasn't a result of the changes in my recent PR.

In order to replicate, render up a basic tilemap with a few tiles, and then do something like:

```
setTimeout(() => 
	tileMap.compositeCache(true);
}, 5000)
```

...and the tilemap disappears. I am looking into this, but thought I'd raise it with you in case there might be something fresh in your mind that could have caused it.

Pete

**Comment by beyond-code-github** [comment]
I think I have tracked down the cause of my issue, we now set this flag to true by default: https://github.com/Irrelon/ige/blob/es6-typescript/engine/core/IgeEngine.ts#L105

Previously this was only set to true by calling `createFrontBuffer` with a falsy `dontScale` parameter. In my case I was creating my own front buffer so this was never being set.

I think I can work around this by setting this flag to false (I tackle high res displays manually using the CSS trick), but I think this will still be an issue for anyone using the IGE-created front buffer and composite caching. Doing this makes the tilemap visible again but it's rendered about 1/4 the size it should be. I'll keep digging.

**Comment by beyond-code-github** [comment]
Also in the mix is this line here: https://github.com/Irrelon/ige/blob/es6-typescript/engine/core/IgeEntity.ts#L1678

```
ctx.drawImage(this._cacheCanvas, -this._bounds2d.x2, -this._bounds2d.y2, this._bounds2d.x, this._bounds2d.y);
```

The old version of the code did not include the last two parameters. Adding these seems to render the cache much smaller than intended. I'm guessing it's a balancing act as all these parts of the code need to work together to get the scaling right.

**Comment by beyond-code-github** [comment]
I think this should be setting `_compositeParent` to true instead of `_compositeCache`:

https://github.com/Irrelon/ige/blob/es6-typescript/engine/core/IgeObject.ts#L850
```
mount (obj: IgeObject): this {
...
...
    if (obj._compositeCache) {
 	this._compositeCache = true;
    } else {
	this._compositeParent = false;
    }
```

With this tweak, I now have the composite cache working on par with the old codebase.

**Comment by Irrelon** [comment]
Merged your PR, please close if that's solved your issue :)

**Comment by beyond-code-github** [comment]
Thanks Rob!
