### ISSUE TITLE
How to detect collision on IgeCannon...?

### ISSUE THREAD

**Issue by KLA6** [Irrelon/ige#482]
I'm sorry, but can I ask a question...?

I've set `index.js` with `IgeCannonComponent` as following.
```
var Game = IgeClass.extend( {
  classId: 'Game',

  init: function ( App, options ) { // Create the engine
    ige = new IgeEngine()
    ige.addComponent( IgeCannonComponent ).cannon.gravity    ( 0, 0, -2000 )
                                          .cannon.createWorld(             )

    if( ige.isClient ) ige.client = new App(         )
    if( ige.isServer ) ige.server = new App( options )
  } // init
} ) // Game
```

By `console.log( ige.cannon._world )`, I could see all `IgeEntityCannon` instants are in `bodies`.

Now I guess the below code patches events of collisions, but it does not.
```
ige.cannon._world.addEventListener( "beginContact", function ( event ) { console.log( event ) } )
```

How can I detect collisions on `IgeCannon`...?

Could you please give me just a short example for it...?

Thank you for reading my question.

**Comment by KLA6** [comment]
I've just found the answer by myself, so I'm leaving here for someone like me in the future.

An `IgeEntityCannon` has `_cannonBody` in it.
And the exact event name of collision is `collide`.
So, you can detect collision as following.

```
self.yourEntity = new IgeEntityCannon()
yourEntity.addEventListener( 'collide', function( event ) { console.log( event ) } )
```

**Comment by Irrelon** [comment]
You beat me to it, only just saw your question, but I’m glad you found the answer!! :)
